server: 
  port: ${EUREKA_PORT1:18761}
eureka: 
  instance:
    hostname: eureka-server-0.eureka-server
  server: 
    renewal-percent-threshold: 0.6   
  client: 
    register-with-eureka: true 
    fetch-registry: true 
    #eureka-server-port: ${server.port}
    service-url:
      defaultZone: ${EUREKA_SERVERS}